-------------------------------------------------------------------------------
Test set: TestSuite
-------------------------------------------------------------------------------
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.065 sec <<< FAILURE! - in TestSuite
Dummy_test_to_fail(test1.runtestes)  Time elapsed: 0.036 sec  <<< FAILURE!
java.lang.AssertionError: expected [2] but found [1]
	at test1.runtestes.Dummy_test_to_fail(runtestes.java:14)

